### ISSUE TITLE
Compilation is too slow

### ISSUE THREAD

**Issue by KeenS** [KeenS/webml#78]
Compile time is good on rust 1.40.0 and bad on 1.41.0.
I guess related to ~~https://github.com/rust-lang/rust/issues/68666~~ https://github.com/rust-lang/rust/issues/69671 .
Needs upstream fix

**Comment by matu3ba** [comment]
Use Flamegraph or hyperfine to measure building.
Likely, if your interface is not that essential, you can use (pico-args)[https://github.com/RazrFalcon/pico-args].

**Comment by KeenS** [comment]
I haven't much investigated, but it seems the trait resolution is slow
![flamegraph](https://user-images.githubusercontent.com/4434568/106348141-59f3c180-6307-11eb-818e-75d0e0723a70.png)

**Comment by KeenS** [comment]
I bisected and found [this commit](https://github.com/rust-lang/rust/commit/05f13a843370995181904ec961a7920eea9ae7bb) introduced this problem. This commit, in turn, is introduced in this PR https://github.com/rust-lang/rust/pull/66408.
